[package]
name = "town-map"
description = "A Rust library for math plotting"
version = "0.0.1"
authors = ["YakoYakoYokuYoku"]
edition = "2018"

[dependencies]
town-map-lib = { path = "town-map-lib", version = "0.0.1" }
num-traits = "0.2.6"
num-complex = "0.2.1"
